// Code generated by tgo DO NOT EDIT.

//line testdata/single_tag.tgo:1:1
package templates

func template(a string) {
	if err := __tgo_ctx.WriteString(`<div></div>`); err != nil {
		return err
	}
//line testdata/single_tag.tgo:5:1
}

func template2(a string) {
	if err := __tgo_ctx.WriteString(`<div></div>`); err != nil {
		return err
	}
//line testdata/single_tag.tgo:10:1
}
