package transpiler

import (
	"fmt"
	"html"
	"math"
	"slices"
	"strconv"
	"strings"

	"github.com/mateusz834/tgo/debug"
	"github.com/mateusz834/tgo/tgofuncs"
	"github.com/mateusz834/tgoast/ast"
	"github.com/mateusz834/tgoast/token"
)

func Transpile(f *ast.File, fs *token.FileSet, src string) string {
	info := tgofuncs.Check(f)

	tgofuncs := make(map[ast.Node]struct{})
	for _, v := range info.TgoFuncs {
		tgofuncs[v] = struct{}{}
	}

	t := transpiler{
		ctx: &transpilerCtx{
			f:   f,
			fs:  fs,
			src: src,

			tgofuncs: tgofuncs,
			tgoIdent: fileUniqueIdent(f, "__tgo_ctx"),
			info:     info,

			out: slices.Grow([]byte{}, len(src)*2),
		},
		lastIndentation: "\n",
	}
	t.transpile()
	if len(t.ctx.tmp) != 0 {
		panic("unreachable")
	}
	return string(t.ctx.out)
}

type transpilerCtx struct {
	f   *ast.File
	fs  *token.FileSet
	src string

	out []byte
	tmp []byte

	tgofuncs                map[ast.Node]struct{}
	info                    tgofuncs.Info
	tgoIdent                string
	tgoAddtionalImportIdent string

	lastPosWritten token.Pos // last position processed by the transpiler of the src.

	// if set to true, then some generated source was written before, and line
	// mapping would get out of sync when appending from original source,
	// before appending anything from src a line directive needs
	// to be written.
	lineDirectiveMangled bool

	inStaticWrite bool // if true, then inside of a static string write call.

	implicitBlockStmtCount            int
	implicitBlockStmtForceCloseBefore int
}

type transpiler struct {
	ctx              *transpilerCtx
	lastIndentation  string // last indentation found in the source, prefixed with a newline.
	additionalIndent int
	inTgoFunc        bool
}

func (t *transpiler) posToOffset(p token.Pos) int {
	return t.ctx.fs.File(t.ctx.f.FileStart).Offset(p)
}

func (t *transpiler) offsetToPos(off int) token.Pos {
	return t.ctx.fs.File(t.ctx.f.FileStart).Pos(off)
}

func (t *transpiler) appendSource(s string) {
	if debug.Verbose {
		fmt.Printf("t.ctx.appendString(%q)\n", s)
	}
	t.flushTmp()
	t.ctx.out = append(t.ctx.out, s...)
}

func (t *transpiler) appendFromSource(end token.Pos) {
	if debug.Verbose {
		fmt.Printf("t.ctx.appendFromSource(%v (%v)) -> ", t.ctx.fs.Position(end), end)
	}
	t.appendSource(t.ctx.src[t.posToOffset(t.ctx.lastPosWritten):t.posToOffset(end)])
	t.ctx.lastPosWritten = end
}

func (t *transpiler) flushTmp() {
	t.ctx.out = append(t.ctx.out, t.ctx.tmp...)
	t.ctx.tmp = t.ctx.tmp[:0]
	t.ctx.implicitBlockStmtForceCloseBefore = t.ctx.implicitBlockStmtCount
}

func (t *transpiler) transpile() {
	// Gopls does not format files that are generated.
	// See: https://go.dev/issue/49555
	t.appendSource("// Code generated by tgo - DO NOT EDIT.\n\n")

	t.ctx.lastPosWritten = t.ctx.f.FileStart
	t.appendSource("//line ")
	t.appendSource(t.ctx.fs.File(t.ctx.f.FileStart).Name())
	t.appendSource(":1:1\n")

	if t.ctx.info.NeedsSpecialTgoImport {
		t.ctx.tgoAddtionalImportIdent = fileUniqueIdent(t.ctx.f, "__tgo")

		i := -1
		for j, v := range t.ctx.f.Decls {
			if v, ok := v.(*ast.GenDecl); ok && v.Tok == token.IMPORT {
				i = j
				break
			}
		}

		if i == -1 || len(t.ctx.f.Decls) == i-1 {
			// NeedsSpecialTgoImport can only be set to true when there is a import
			// and when more decls exist (there must be a tgo func).
			panic("unreachable")
		}

		cur, next := t.ctx.f.Decls[i].(*ast.GenDecl), t.ctx.f.Decls[i+1]

		//TODO: cur.End() == next.ctx.Pos()

		var last iterWhiteResult
	outer:
		for last = range t.iterWhite(cur.End(), next.Pos()) {
			switch last.whiteType {
			case whiteWhite:
			case whiteComment:
			case whiteSemi:
			case whiteIndent:
				break outer
			}
		}

		t.appendFromSource(last.pos)
		t.appendSource("\n\nimport ")
		t.appendSource(t.ctx.tgoAddtionalImportIdent)
		t.appendSource(" \"github.com/mateusz834/tgo\"\n")
		t.writeLineDirective(lineDirectiveFullLine, last.pos)

		// TODO: this logic beloow is bad bad bad
		// we need to do this differenlty and better
	}

	ast.Walk(t, t.ctx.f)
	t.appendFromSource(t.ctx.f.FileEnd)

	needsErrorAssert := false
	for v := range t.ctx.tgofuncs {
		switch v := v.(type) {
		case *ast.FuncLit:
			if v, ok := v.Type.Results.List[0].Type.(*ast.Ident); ok && v.Name == "error" {
				needsErrorAssert = true
				break
			}
		case *ast.FuncDecl:
			if v, ok := v.Type.Results.List[0].Type.(*ast.Ident); ok && v.Name == "error" {
				needsErrorAssert = true
				break
			}
		}
	}

	if needsErrorAssert {
		// TODO: import ident should not be static.
		t.appendSource(`
// Assert that no other file in this package overrides the error builtin interface.
var _ = (*tgo.Error)((*error)(nil))
`)
	}
}

func (t *transpiler) addLineDirectiveBeforeRbrace(rbracePos token.Pos) {
	if t.ctx.lineDirectiveMangled {
		r := t.whiteAlg(t.ctx.lastPosWritten, rbracePos)
		t.writeLineDirective(r.ld, t.ctx.lastPosWritten)
		t.ctx.inStaticWrite = false
		t.ctx.lineDirectiveMangled = false
	}
}

func (t *transpiler) tgoFunc(n ast.Node, funcType *ast.FuncType, body *ast.BlockStmt) {
	if body == nil {
		return
	}

	indentation := t.blockIndent(body)

	if _, ok := t.ctx.tgofuncs[n]; ok {
		needsCtx := false
		ast.Inspect(n, func(x ast.Node) bool {
			if isTgo(x, true) {
				needsCtx = true
				return false
			}
			if _, ok := x.(*ast.FuncLit); ok && n != x {
				return false
			}
			return true
		})
		if !needsCtx {
			ast.Walk(&transpiler{
				ctx:             t.ctx,
				lastIndentation: indentation,
				inTgoFunc:       true,
			}, body)
			return
		}

		params := funcType.Params
		param := params.List[0]
		if param.Names == nil {
			t.appendFromSource(param.Type.Pos())
			t.appendSource(t.ctx.tgoIdent)
			t.writeLineDirective(lineDirectiveOneLineLRSpace, param.Type.Pos())
			t.appendFromSource(params.Closing)
		} else if param.Names[0].Name == "_" {
			t.appendFromSource(params.List[0].Names[0].Pos())
			t.appendSource(t.ctx.tgoIdent)
			t.ctx.lastPosWritten = params.List[0].Names[0].End()
			ld := lineDirectiveOneLineLSpace
			if len(params.List) == 0 {
				ld = lineDirectiveOneLineLRSpace
			}
			t.writeLineDirective(ld, params.List[0].Names[0].End())
			t.appendFromSource(params.Closing)
		} else {
			t := &transpiler{
				ctx:             t.ctx,
				lastIndentation: indentation,
				inTgoFunc:       true,
			}
			t.appendFromSource(body.Lbrace + 1)
			t.transpileList(body.List, params.List[0].Names[0].Name)
			t.addLineDirectiveBeforeRbrace(body.Rbrace)
			t.appendFromSource(body.Rbrace + 1)
			return
		}
		ast.Walk(&transpiler{
			ctx:             t.ctx,
			lastIndentation: indentation,
			inTgoFunc:       true,
		}, body)
		return
	}
	ast.Walk(&transpiler{
		ctx:             t.ctx,
		lastIndentation: indentation,
		inTgoFunc:       false,
	}, body)
}

func (t *transpiler) Visit(n ast.Node) ast.Visitor {
	t.ctx.inStaticWrite = false
	defer func() {
		t.ctx.inStaticWrite = false
	}()
	switch n := n.(type) {
	case *ast.FuncDecl:
		t.tgoFunc(n, n.Type, n.Body)
		return nil
	case *ast.FuncLit:
		t.tgoFunc(n, n.Type, n.Body)
		return nil
	case *ast.BlockStmt:
		// TODO: line directive before this and what about *ast.SwitchStmt and TypeSwitchStmt.ctx.
		t := &transpiler{
			ctx:             t.ctx,
			lastIndentation: t.blockIndent(n),
			inTgoFunc:       t.inTgoFunc,
		}
		t.appendFromSource(n.Lbrace + 1)
		t.transpileList(n.List, "")
		t.addLineDirectiveBeforeRbrace(n.Rbrace)
		t.appendFromSource(n.Rbrace + 1)
		return nil
	}
	return t
}

type lineDirective uint8

const (
	_ lineDirective = iota

	lineDirectiveFullLine       // "//line file:line:col\n"
	lineDirectiveOneLine        // "/*line file:line:col*/"
	lineDirectiveOneLineLSpace  // " /*line file:line:col*/"
	lineDirectiveOneLineRSpace  // "/*line file:line:col*/ "
	lineDirectiveOneLineLRSpace // " /*line file:line:col*/ "
)

func (t *transpiler) writeLineDirective(ld lineDirective, pos token.Pos) {
	switch ld {
	case lineDirectiveOneLineLSpace, lineDirectiveOneLine:
		pos -= 1
	case lineDirectiveOneLineRSpace, lineDirectiveOneLineLRSpace:
		if t.ctx.fs.Position(pos+1).Column-2 <= 0 {
			pos++
			ld = lineDirectiveOneLine
		}
		pos -= 2
	case lineDirectiveFullLine:
	default:
		panic("unreachable")
	}

	p := t.ctx.fs.Position(pos + 1)
	if ld == lineDirectiveOneLineLSpace || ld == lineDirectiveOneLineLRSpace {
		t.appendSource(" /*line ")
	} else if ld == lineDirectiveOneLineRSpace || ld == lineDirectiveOneLine {
		t.appendSource("/*line ")
	} else {
		t.appendSource("\n//line ")
	}

	t.appendSource(":")
	t.appendSource(strconv.FormatInt(int64(p.Line), 10))
	t.appendSource(":")
	t.appendSource(strconv.FormatInt(int64(p.Column), 10))

	if ld == lineDirectiveOneLineRSpace || ld == lineDirectiveOneLineLRSpace {
		t.appendSource("*/ ")
	} else if ld == lineDirectiveOneLineLSpace || ld == lineDirectiveOneLine {
		t.appendSource("*/")
	}
}

func (t *transpiler) appendIndent(b []byte) []byte {
	b = append(b, t.lastIndentation...)
	for range t.additionalIndent {
		b = append(b, '\t')
	}
	return b
}

func (t *transpiler) wantIndent() {
	if debug.Verbose {
		fmt.Printf(
			"t.ctx.wantIndent(%v): appending %q\n",
			t.additionalIndent,
			t.lastIndentation+strings.Repeat("\t", t.additionalIndent),
		)
	}
	t.flushTmp()
	t.ctx.out = t.appendIndent(t.ctx.out)
}

func isTgo(n ast.Node, inTgoFunc bool) bool {
	switch n := n.(type) {
	case *ast.OpenTagStmt, *ast.EndTagStmt, *ast.AttributeStmt:
		return true
	case *ast.ExprStmt:
		x, isBasicLit := n.X.(*ast.BasicLit)
		_, isTemplate := n.X.(*ast.TemplateLiteralExpr)
		return (isBasicLit && x.Kind == token.STRING && inTgoFunc) || isTemplate
	}
	return false
}

type scopeState struct {
	beforeLen int
}

func (t *transpiler) scopeStart() scopeState {
	beforeLen := len(t.ctx.tmp)
	t.ctx.tmp = t.appendIndent(t.ctx.tmp)
	t.ctx.tmp = append(t.ctx.tmp, '{')
	t.ctx.implicitBlockStmtCount++
	return scopeState{
		beforeLen: beforeLen,
	}
}

func (t *transpiler) scopeEnd(s scopeState) {
	if t.ctx.implicitBlockStmtCount <= t.ctx.implicitBlockStmtForceCloseBefore {
		t.ctx.tmp = t.appendIndent(t.ctx.tmp)
		t.ctx.tmp = append(t.ctx.tmp, '}')
		t.ctx.implicitBlockStmtForceCloseBefore--
	} else {
		if debug.Debug {
			for _, v := range t.ctx.tmp[s.beforeLen:] {
				switch v {
				case ' ', '\t', '\n', '{', '}':
				default:
					panic("unreachable")
				}
			}
		}
		t.ctx.tmp = t.ctx.tmp[:s.beforeLen]
	}
	t.ctx.implicitBlockStmtCount--
}

func unlabel(n ast.Stmt) (ast.Stmt, token.Pos) {
	lastLabelPos := token.NoPos
	for {
		if l, ok := n.(*ast.LabeledStmt); ok {
			n = l.Stmt
			lastLabelPos = l.Colon + 1
			continue
		}
		break
	}
	return n, lastLabelPos
}

type whiteAlgResult struct {
	ld                   lineDirective
	lastNewlineOrNodePos token.Pos
}

func (t *transpiler) whiteAlg(start, end token.Pos) whiteAlgResult {
	var (
		onelineDirective = t.ctx.fs.Position(start).Line == t.ctx.fs.Position(end).Line

		// Note that the current implementation is wrong in case of a multiline
		// comment, it is not a problem for what we are using it now.
		beforeNewline = true

		firstWhite           = false
		afterFirst           = false
		lastNewlineOrNodePos = start
	)

	for v := range t.iterWhite(start, end) {
		switch v.whiteType {
		case whiteWhite:
			if beforeNewline {
				onelineDirective = true
			}
			if !afterFirst {
				firstWhite = true
			}
		case whiteIndent:
			//t.lastIndentation = v.text
			beforeNewline = false
			lastNewlineOrNodePos = v.pos
		case whiteComment:
			if beforeNewline {
				onelineDirective = true
			}
		case whiteSemi:
			if beforeNewline {
				onelineDirective = true
			}
		default:
			panic("unreachable")
		}
		afterFirst = true
	}

	ld := lineDirectiveFullLine
	if onelineDirective {
		ld = lineDirectiveOneLineLRSpace
		if firstWhite {
			ld = lineDirectiveOneLineLSpace
		}
	}

	return whiteAlgResult{
		ld:                   ld,
		lastNewlineOrNodePos: lastNewlineOrNodePos,
	}
}

func (t *transpiler) transpileList(list []ast.Stmt, name string) {
	var (
		prev      ast.Node
		bodyScope = make([]scopeState, 0, 16)
	)
	for i, n := range list {
		orig := n
		p := t.ctx.lastPosWritten
		wasLabeled := false
		if unlabeled, lastLabelEndPos := unlabel(n); lastLabelEndPos.IsValid() && isTgo(unlabeled, t.inTgoFunc) {
			p = lastLabelEndPos
			n = unlabeled
			wasLabeled = true
			t.ctx.inStaticWrite = false
			t.ctx.lineDirectiveMangled = true
		}

		r := t.whiteAlg(p, n.Pos())

		if i == 0 && name != "" {
			var (
				lastCommentEndPos = p
				lastIndent        bool
				lastWhite         bool
			)
			for v := range t.iterWhite(p, n.Pos()) {
				lastIndent = false
				lastWhite = false
				switch v.whiteType {
				case whiteWhite:
					lastWhite = true
				case whiteIndent:
					lastIndent = true
					lastCommentEndPos = v.pos
				case whiteComment:
					lastCommentEndPos = v.end()
				case whiteSemi:
				default:
					panic("unreachable")
				}
			}

			t.appendFromSource(lastCommentEndPos)
			t.wantIndent()
			t.appendSource(t.ctx.tgoIdent)
			t.appendSource(" := ")
			t.appendSource(name)
			if !isTgo(n, t.inTgoFunc) {
				r.ld = lineDirectiveOneLineRSpace
				if lastIndent {
					r.ld = lineDirectiveFullLine
				} else if lastWhite {
					r.ld = lineDirectiveOneLine
					t.wantIndent()
				} else {
					t.wantIndent()
				}
			}
			t.ctx.lineDirectiveMangled = true
			r.lastNewlineOrNodePos = lastCommentEndPos
		}

		// TODO: chyba najlepiej bd wyniesć ten endtag gdzies wysoko?

		if isTgo(n, t.inTgoFunc) {
			// When previous node was non-tgo and now we have a tgo node,
			// preserve whitespace, comments and semicolons up to last newline
			// (or up to n.Pos() if no newline found between prev and n).
			_, isEndTag := n.(*ast.EndTagStmt)
			if !isTgo(prev, t.inTgoFunc) && !(isEndTag && wasLabeled) || (wasLabeled && !isEndTag && isTgo(prev, t.inTgoFunc)) {
				if isTgo(prev, t.inTgoFunc) {
					t.writeLineDirective(r.ld, t.ctx.lastPosWritten)
				}
				t.appendFromSource(r.lastNewlineOrNodePos)
			}

			// TODO: we are ingnoring comments between tgo tags.

			// When the current node is a tgo-node, ignore the whitespace
			// the logic below will add the indentation (from t.ctx.lastIndentation),
			// when necessary.
			t.ctx.lineDirectiveMangled = true
		} else {
			if t.ctx.lineDirectiveMangled {
				t.ctx.inStaticWrite = false
				t.ctx.lineDirectiveMangled = false
				t.writeLineDirective(r.ld, t.ctx.lastPosWritten)
			}
		}

		switch n := n.(type) {
		case *ast.OpenTagStmt:
			t.staticWriteIndent("<")
			t.staticWriteIndent(n.Name.Name)

			tagScope := t.scopeStart()
			t.ctx.lastPosWritten = n.Name.End()

			t.additionalIndent++
			t.transpileList(n.Body, "")
			t.additionalIndent--

			for v := range t.iterWhite(t.ctx.lastPosWritten, n.ClosePos) {
				if v.whiteType == whiteIndent {
					t.lastIndentation = v.text
				} else {
					continue
					// TODO: figure case this out.ctx.
					panic("unreachable")
				}
			}

			t.scopeEnd(tagScope)

			t.staticWriteIndent(">")
			bodyScope = append(bodyScope, t.scopeStart())
			t.additionalIndent++
			t.ctx.lastPosWritten = n.End()
		case *ast.EndTagStmt:
			t.additionalIndent--

			t.scopeEnd(bodyScope[len(bodyScope)-1])
			bodyScope = bodyScope[:len(bodyScope)-1]

			if wasLabeled {
				if t.ctx.lineDirectiveMangled {
					before := t.lastIndentation
					r := t.whiteAlg(t.ctx.lastPosWritten, orig.Pos())
					t.lastIndentation = before
					t.writeLineDirective(r.ld, t.ctx.lastPosWritten)
				}
				t.appendFromSource(r.lastNewlineOrNodePos)
			}

			t.staticWriteIndent("</")
			t.staticWriteIndent(n.Name.Name)
			t.staticWriteIndent(">")
			t.ctx.lastPosWritten = n.End()
		case *ast.AttributeStmt:
			if n.Value != nil {
				switch x := n.Value.(type) {
				case *ast.BasicLit:
					t.staticWriteIndent(" ")
					t.staticWriteIndent(n.AttrName.(*ast.Ident).Name)
					t.staticWriteIndent("=")
					if x.Kind == token.STRING {
						t.staticWriteIndentGoString(x.Value)
					}
				case *ast.TemplateLiteralExpr:
					t.staticWriteIndent(" " + n.AttrName.(*ast.Ident).Name + "=")
					t.transpileTemplateLiteral(x)
				}
			} else {
				t.staticWriteIndent(" ")
				t.staticWriteIndent(n.AttrName.(*ast.Ident).Name)
			}
			t.ctx.lastPosWritten = n.End()
		case *ast.ExprStmt:
			if x, ok := n.X.(*ast.BasicLit); ok && x.Kind == token.STRING {
				if t.inTgoFunc {
					t.staticWriteIndentGoString(x.Value)
					t.ctx.lastPosWritten = n.End()
				} else {
					t.appendFromSource(n.End())
				}
			} else if x, ok := n.X.(*ast.TemplateLiteralExpr); ok {
				t.transpileTemplateLiteral(x)
			} else {
				ast.Walk(t, n)
				t.appendFromSource(n.End())
				t.ctx.lastPosWritten = n.End()
			}
		case *ast.CaseClause:
			for _, v := range n.List {
				ast.Walk(t, v)
			}
			t.appendFromSource(n.Colon + 1)
			t.transpileList(n.Body, "")
		case *ast.CommClause:
			if n.Comm != nil {
				ast.Walk(t, n.Comm)
			}
			t.appendFromSource(n.Colon + 1)
			t.transpileList(n.Body, "")
		default:
			ast.Walk(t, n)
			t.appendFromSource(n.End())
			t.ctx.lastPosWritten = n.End()
		}

		prev = n
	}
}

func (t *transpiler) transpileTemplateLiteral(x *ast.TemplateLiteralExpr) {
	for i := range x.Parts {
		if i == 0 {
			t.staticWriteIndentGoString(x.Strings[i] + "\"")
		} else {
			t.staticWriteIndentGoString("\"" + x.Strings[i] + "\"")
		}
		t.ctx.inStaticWrite = false
		t.dynamicWriteIndent(x, x.Parts[i])
	}
	t.staticWriteIndentGoString("\"" + x.Strings[len(x.Strings)-1])
	t.ctx.lastPosWritten = x.End()
}

func (t *transpiler) dynamicWriteIndent(x *ast.TemplateLiteralExpr, n *ast.TemplateLiteralPart) {
	t.wantIndent()

	t.appendSource("if err := ")
	if d, ok := t.ctx.info.UsableImportForTemplate[x]; ok {
		if d.DotImport {
			t.appendSource("DynamicWrite(")
		} else {
			t.appendSource(d.ImportIdent)
			t.appendSource(".DynamicWrite(")
		}
	} else if t.ctx.info.NeedsSpecialTgoImport {
		t.appendSource(t.ctx.tgoAddtionalImportIdent)
		t.appendSource(".DynamicWrite(")
	} else {
		panic("unreachable")
	}

	t.appendSource(t.ctx.tgoIdent)
	t.appendSource(", " +
		// We wrap n in parentheses to create a *ast.ParenExpr,
		// because the Go parser does not preserve the position of commas.
		// Without the parentheses, comments get moved before the comma during formatting.
		// See: https://go.dev/issue/13113
		"(",
	)

	t.ctx.lastPosWritten = n.LBrace + 1
	lineDirectivePos := t.ctx.lastPosWritten

	var prev iterWhiteResult
	for v := range t.iterWhite(t.ctx.lastPosWritten, n.X.Pos()) {
		if prev.whiteType != whiteInvalid {
			if prev.whiteType == whiteWhite && prev.text == " " && v.whiteType == whiteComment {
				// Comment prefixed with a space, skip it, so we
				// don't end up with two spaces in a row.
				t.ctx.lastPosWritten++
			}
			break
		}
		prev = v
	}

	t.writeLineDirective(lineDirectiveOneLineLRSpace, lineDirectivePos)

	// TODO: figure out whether t.ctx.lineDirectiveMangled behaves right with this.

	t.appendFromSource(n.X.Pos())
	indent := t.lastIndentation
	ast.Walk(t, n)
	t.lastIndentation = indent
	t.appendFromSource(n.End() - 1)

	t.appendSource(")); err != nil {")
	t.wantIndent()
	t.appendSource("\treturn err")
	t.wantIndent()
	t.appendSource("}")
}

func (t *transpiler) staticWriteIndentGoString(s string) {
	s, err := strconv.Unquote(s)
	if err != nil {
		panic(err) // unreachable, AST is valid
	}
	s = strconv.Quote(html.EscapeString(s))
	t.staticWriteIndent(s[1 : len(s)-1])
}

func (t *transpiler) staticWriteIndent(s string) {
	if t.ctx.inStaticWrite {
		t.ctx.out = append(t.ctx.out, s...)
		return
	}
	t.ctx.inStaticWrite = true
	t.wantIndent()
	t.appendSource("if err := ")
	t.appendSource(t.ctx.tgoIdent)
	t.appendSource(".WriteString(\"")
	t.appendSource(s)
	t.ctx.tmp = append(t.ctx.tmp, "\"); err != nil {"...)
	t.ctx.tmp = t.appendIndent(t.ctx.tmp)
	t.ctx.tmp = append(t.ctx.tmp, "\treturn err"...)
	t.ctx.tmp = t.appendIndent(t.ctx.tmp)
	t.ctx.tmp = append(t.ctx.tmp, '}')
}

func (t *transpiler) blockIndent(b *ast.BlockStmt) string {
	start := b.Lbrace + 1
	if len(b.List) != 0 {
		start = b.List[len(b.List)-1].End()
	}

	lastIndent := ""
	for v := range t.iterWhite(start, b.Rbrace) {
		lastIndent = ""
		switch v.whiteType {
		case whiteIndent:
			lastIndent = v.text
		}
	}

	if lastIndent != "" {
		return lastIndent + "\t"
	}

	return t.lastIndentation + "\t"
}

func fileUniqueIdent(f *ast.File, defaultIdent string) string {
	used := false
	ast.Inspect(f, func(n ast.Node) bool {
		switch n := n.(type) {
		case *ast.Ident:
			if n.Name == defaultIdent {
				used = true
				return false
			}
		}
		return true
	})
	if !used {
		return defaultIdent
	}

	usedIdents := make(map[string]struct{})
	ast.Inspect(f, func(n ast.Node) bool {
		switch n := n.(type) {
		case *ast.Ident:
			usedIdents[n.Name] = struct{}{}
		}
		return true
	})

	for i := range uint(math.MaxUint) {
		ident := defaultIdent + strconv.FormatUint(uint64(i), 10)
		if _, ok := usedIdents[ident]; !ok {
			return ident
		}
	}

	panic("unreachable")
}
