package transpiler

import (
	"errors"
	"io"
	"math"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	goast "go/ast"
	"go/build/constraint"
	goformat "go/format"
	goparser "go/parser"
	goscanner "go/scanner"
	gotoken "go/token"

	"github.com/mateusz834/tgo/analyzer"
	"github.com/mateusz834/tgoast/ast"
	"github.com/mateusz834/tgoast/format"
	"github.com/mateusz834/tgoast/parser"
	"github.com/mateusz834/tgoast/scanner"
	"github.com/mateusz834/tgoast/token"
)

// TODO: transpilation of:
//func A(A){"\{a}\{""}l"}
//func a(a string) { "a" }

func test() {
	// Transpile string writes to something like this,
	// this way we can also preserve comments, by adding them
	// betwen strings.
	io.WriteString(nil, ""+
		"<div"+
		" attr=\"value\""+
		" attr=\"valuedf\""+
		">"+
		"<span>"+
		"value between div"+
		"</span>"+
		"</div>",
	)
}

const tgosrc = `
package A

func a(a string) {
	<div>
		/*test*/ a()
	</div>
}
`

//const tgosrc = "// Code generated by tgo DO NOT EDIT.\n\n//line 0:1:1\npackage A\nimport()//0\nfunc()A(){switch{case 0:0//go:build\n0}}"

func TestTranspiler(t *testing.T) {
	fs := token.NewFileSet()
	f, err := parser.ParseFile(fs, "test.tgo", tgosrc, parser.SkipObjectResolution|parser.ParseComments)

	ast.Print(fs, f)

	if err != nil {
		if v, ok := err.(scanner.ErrorList); ok {
			for _, err := range v {
				t.Errorf("%v", err)
			}
		}
		t.Fatalf("%v", err)
	}

	err = analyzer.Analyze(fs, f)
	err = nil
	if v, ok := err.(analyzer.AnalyzeErrors); ok {
		for _, v := range v {
			t.Logf("%v", v)
		}
	}
	if err != nil {
		t.Fatalf("%v", err)
	}

	t.Log("\n" + string(tgosrc))
	fmted, err := format.Source([]byte(tgosrc))
	if err != nil {
		t.Fatalf("%v", err)
	}
	t.Log("\n" + string(fmted))

	var oo strings.Builder
	if err := format.Node(&oo, fs, f); err != nil {
		t.Fatal(err)
	}
	t.Log("\n" + oo.String())

	out := Transpile(f, fs, tgosrc)
	t.Log("\n" + out)
	t.Logf("\n%q", out)

	fs = token.NewFileSet()
	f, err = parser.ParseFile(fs, "test.go", out, parser.SkipObjectResolution|parser.ParseComments)
	if err != nil {
		if v, ok := err.(scanner.ErrorList); ok {
			for _, err := range v {
				t.Errorf("%v", err)
			}
		}
		t.Fatalf("%v", err)
	}

	ast.Print(fs, f)

	var o strings.Builder
	if err := format.Node(&o, fs, f); err != nil {
		t.Fatal(err)
	}
	t.Log("\n" + o.String())

	if o.String() != out {
		t.Log(gitDiff(t.TempDir(), o.String(), out))
		t.Fatal("difference found")
	}
}

func gitDiff(tmpDir string, got, expect string) (string, error) {
	gotPath := filepath.Join(tmpDir, "got")
	gotFile, err := os.Create(gotPath)
	if err != nil {
		return "", err
	}
	defer gotFile.Close()
	if _, err := gotFile.WriteString(got); err != nil {
		return "", err
	}

	expectPath := filepath.Join(tmpDir, "expect")
	expectFile, err := os.Create(expectPath)
	if err != nil {
		return "", err
	}
	defer expectFile.Close()
	if _, err := expectFile.WriteString(expect); err != nil {
		return "", err
	}

	var out strings.Builder
	cmd := exec.Command("git", "diff", "-U 100000", "--no-index", "--color=always", "--ws-error-highlight=all", gotPath, expectPath)
	cmd.Stdout = &out
	if err := cmd.Run(); err != nil && cmd.ProcessState.ExitCode() != 1 {
		return "", err
	}
	return out.String(), nil
}

func TestTranspile(t *testing.T) {
	const testdata = "./testdata"
	files, err := os.ReadDir(testdata)
	if err != nil {
		t.Fatal(err)
	}

	for _, v := range files {
		ext := filepath.Ext(v.Name())
		if ext != ".tgo" {
			continue
		}

		testFile := filepath.Join(testdata, v.Name())
		expectFileName := filepath.Join(testdata, v.Name()[:len(v.Name())-len(".tgo")]+".go")
		t.Run(testFile, func(t *testing.T) {
			content, err := os.ReadFile(testFile)
			if err != nil {
				t.Fatal(err)
			}
			t.Logf("%v:\n%s", testFile, content)

			fs := token.NewFileSet()
			f, err := parser.ParseFile(fs, testFile, content, parser.ParseComments|parser.SkipObjectResolution)
			if err != nil {
				t.Fatal(err)
			}

			out := Transpile(f, fs, string(content))
			t.Logf("transpiled %v:\n%s", testFile, out)

			expect, err := os.ReadFile(expectFileName)
			if err != nil {
				if errors.Is(err, os.ErrNotExist) {
					if err := os.WriteFile(expectFileName, []byte(out), 06660); err != nil {
						t.Fatal(err)
					}
					return
				}
				t.Fatal(err)
			}

			if out != string(expect) {
				t.Log("make following changes to make this test pass:")
				t.Log(gitDiff(t.TempDir(), out, string(expect)))
				t.Fatal("difference found")
			}
		})
	}
}

func fuzzAddDir(f *testing.F, testdata string) {
	files, err := os.ReadDir(testdata)
	if err != nil {
		f.Fatal(err)
	}
	for _, v := range files {
		if v.IsDir() {
			continue
		}

		testFile := filepath.Join(testdata, v.Name())
		content, err := os.ReadFile(testFile)
		if err != nil {
			f.Fatal(err)
		}
		f.Add(testFile, string(content))
	}
}

func FuzzFormattedTgoProducesFormattedGoSource(f *testing.F) {
	fuzzAddDir(f, "../../tgoast/printer/testdata/tgo")
	fuzzAddDir(f, "../../tgoast/parser/testdata/tgo")
	fuzzAddDir(f, "../../tgoast/printer")
	fuzzAddDir(f, "../../tgoast/printer/testdata")
	fuzzAddDir(f, "../../tgoast/parser")
	fuzzAddDir(f, "../../tgoast/parser/testdata")
	fuzzAddDir(f, "../../tgoast/ast")

	f.Add("a", `package main

func a() {
	"000"
	//
}
`)

	f.Add("a", `

// test
package main
`)

	f.Fuzz(func(t *testing.T, name string, src string) {
		t.Logf("file name: %q", name)

		if _, err := parser.ParseFile(
			token.NewFileSet(),
			name,
			"//line "+name+":1:1\n/*line "+name+":1:1*/\npackage main",
			parser.ParseComments|parser.SkipObjectResolution,
		); err != nil ||
			strings.ContainsRune(name, '\r') || strings.ContainsRune(src, '\r') ||
			strings.ContainsRune(name, '\f') || strings.ContainsRune(name, '\n') ||
			strings.ContainsRune(name, '`') || strings.ContainsRune(name, '\'') ||
			strings.Contains(name, "*/") {
			return
		}

		t.Logf("source:\n%v", src)
		t.Logf("quoted input:\n%q", src)

		fs := token.NewFileSet()
		f, err := parser.ParseFile(fs, name, src, parser.ParseComments|parser.SkipObjectResolution)
		if err != nil {
			return
		}

		if analyzer.Analyze(fs, f) != nil {
			return
		}

		emptyBlockStmtCount := 0
		ast.Inspect(f, func(n ast.Node) bool {
			switch n := n.(type) {
			case *ast.BlockStmt:
				if len(n.List) == 0 {
					emptyBlockStmtCount++
				}
			case *ast.BasicLit:
				if strings.ContainsRune(n.Value, '`') {
					t.Skip()
				}
				if n.Kind == token.STRING && n.Value[0] == '"' && strings.ContainsRune(n.Value, '\f') {
					t.Skip()
				}
			case *ast.TemplateLiteralExpr:
				for _, v := range n.Strings {
					if strings.ContainsRune(v, '`') {
						t.Skip()
					}
				}
			}
			return true
		})

		out := Transpile(f, fs, src)
		t.Logf("transpiled output:\n%v", out)
		t.Logf("quoted transpiled output:\n%q", out)

		fsgo := gotoken.NewFileSet()
		fgo, err := goparser.ParseFile(fsgo, name, out, goparser.ParseComments|goparser.SkipObjectResolution)
		if err != nil {
			if v, ok := err.(goscanner.ErrorList); ok {
				for _, v := range v {
					t.Logf("%v", v)
				}
			}
			t.Logf("quoted transpiled output:\n%q", out)
			t.Fatalf("goparser.ParseFile() = %v; want <nil>", err)
		}

		emptyBlockStmtCountGo := 0
		goast.Inspect(fgo, func(n goast.Node) bool {
			switch n := n.(type) {
			case *goast.BlockStmt:
				if len(n.List) == 0 {
					emptyBlockStmtCountGo++
				}
			}
			return true
		})

		// Transpiler should not produce empty block stmts for empty tags (<div>)
		// and for empty tag bodies (<div></div>).
		if emptyBlockStmtCount != emptyBlockStmtCountGo {
			t.Error("transpiled output contains unexpected empty *ast.BlockStmt")
		}

		// NOTE: this case is already handled by //line check below.
		// Because of the go doc formatting rules it is currently impossible
		// with the curreent golang formatter to make sure that the comments
		// before the package token do not cause different formatting when
		// the line directive is prepended.
		//for _, v := range f.Comments {
		//	for _, v := range v.List {
		//		if v.Pos() > f.Package {
		//			break
		//		}
		//		return
		//	}
		//}

		// TODO: understand this issue, is this related to the ast.SortImprts panic?
		for _, v := range f.Comments {
			for _, v := range v.List {
				if v.Text[1] == '*' && strings.ContainsRune(v.Text, '\f') {
					return
				}
			}
		}

		// The Go formatter moves comments around, bacause it treats every comment
		// at Column == 1 as doc comment, and it moves directives to the end of a comment.
		// Line directive should not be moved in any way (https://go.dev/cl/609077).
		// We are not able to keep that formatted.
		// Also comments with line directives are not properly combined
		// into comment groups, because of line directives (https://go.dev/cl/609515)
		prevHadLine := false
		prevLine := math.MinInt
		for _, v := range fgo.Comments {
			if prevHadLine && prevLine+1 == fsgo.PositionFor(v.Pos(), false).Line {
				return
			}
			prevHadLine = false
			prevLine = fsgo.PositionFor(v.End(), false).Line

			for _, c := range v.List {
				p := fsgo.PositionFor(v.Pos(), false)
				if (p.Column == 1 && strings.HasPrefix(c.Text, "//line")) || strings.HasPrefix(c.Text, "/*line") {
					if len(v.List) != 1 {
						return
					}
					prevHadLine = true
				}
			}
		}

		var tgoFmt strings.Builder
		func() {
			defer func() {
				if p := recover(); p != nil {
					b := make([]uintptr, 128)
					n := runtime.Callers(0, b)
					cf := runtime.CallersFrames(b[:n])
					for f, ok := cf.Next(); ok; f, ok = cf.Next() {
						v, _ := p.(string)

						// Upstream bugs:

						// https://go.dev/cl/610035
						if f.Func.Name() == "github.com/mateusz834/tgoast/ast.sortSpecs" &&
							strings.Contains(v, "invalid line number") {
							return
						}

						// https://go.dev/cl/610115 https://go.dev/issue/69206
						if f.Func.Name() == "github.com/mateusz834/tgoast/printer.combinesWithName" &&
							strings.Contains(v, "unexpected parenthesized expression") {
							return
						}
					}
					panic(p)
				}
			}()
			if err := format.Node(&tgoFmt, fs, f); err != nil {
				// See https://go.dev/issue/69089
				if strings.Contains(err.Error(), "format.Node internal error (") {
					for _, v := range f.Comments {
						for _, v := range v.List {
							if fs.PositionFor(v.Pos(), false).Column != 1 &&
								(constraint.IsGoBuild(v.Text) || constraint.IsPlusBuild(v.Text)) {
								return
							}
						}
					}
				}
				t.Fatalf("format.Node() = %v; want <nil>", err)
			}
		}()

		if tgoFmt.String() != src {
			return // input src not formatted
		}

		var outFmt strings.Builder
		if err := goformat.Node(&outFmt, fsgo, fgo); err != nil {
			t.Fatalf("goformat.Node() = %v; want <nil>", err)
		}

		t.Logf("formatted transpiled output:\n%v", outFmt.String())
		t.Logf("quoted transpiled output:\n%q", out)
		t.Logf("quoted formatted transpiled output:\n%q", outFmt.String())

		if outFmt.String() != out {
			diff, err := gitDiff(t.TempDir(), out, outFmt.String())
			if err != nil {
				t.Fatalf("difference found")
			}
			t.Fatalf(
				"difference found, apply following changes to make this test pass:\n%v",
				diff,
			)
		}
	})
}
